let payAbilityList = [
  { project: '年初资产', line: '（1）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '年度内资产变化', line: '（2）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '年末资产', line: '（3）＝（2）＋（1）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '非认可资产', line: '（4）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '认可资产', line: '（5）＝（3）-（4）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '责任准备金', line: '（6）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '独立帐户负债', line: '（7）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '资本性负债', line: '（8）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '保户储金及投资款', line: '（9）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '其他认可负债', line: '（10）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '认可负债', line: '(11)=(6)+(7)+(8)+(9)+(10)', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '实际资本', line: '（12）=（5）－（11）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '核心资本', line: '（13）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '最低资本', line: '（14）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '综合偿付能力溢额', line: '（15）=（12）－（14）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '核心偿付能力溢额', line: '（16）=（13）－（14）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '综合偿付能力充足率', line: '（17）=（12）/（14）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' },
  { project: '核心偿付能力充足率', line: '（18）=（13）/（14）', reportYearLine: '', reportFirstYear: '', reportSecondYear: '' }
]
let forcastLowCapitalList = [
  {line: '1', project: '量化风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1', project: '保险风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1', project: '保费风险和准备金风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.1', project: '其中：车险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.2', project: '财产险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.3', project: '船货特险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.4', project: '责任险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.5', project: '农业险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.6', project: '信用保证险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.7', project: '短意险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.8', project: '短健险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.9', project: '短寿险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.1.10', project: '其他险', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.1.2', project: '巨灾风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2', project: '市场风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.1', project: '利率风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.2', project: '权益价格风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.3', project: '房地产价格风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.4', project: '境外固定收益类资产价格风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.5', project: '境外权益类资产价格风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.2.6', project: '汇率风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.3', project: '信用风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.3.1', project: '利差风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '1.3.2', project: '交易对手违约风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '2', project: '控制风险最低资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '3', project: '附加资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '3.1', project: '逆周期附加资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '3.2', project: '国内系统重要性保险机构附加资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '3.3', project: '国际系统重要性保险机构附加资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '3.4', project: '其他附加资本', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''},
  {line: '4', project: '最低资本合计', reportYearLine: '', reportFirstYear: '', reportSecondYear: ''}
]
export default{
  payAbilityList,
  payAbilityKey: [
    { key: 'bYearAsset', project: '年初资产' },
    { key: 'assetChange', project: '年度内资产变化' },
    { key: 'eYearAsset', project: '年末资产' },
    { key: 'unAcceptAsset', project: '非认可资产' },
    { key: 'acceptAsset', project: '认可资产' },
    { key: 'dutyPrepare', project: '责任准备金' },
    { key: 'selfAccountDebt', project: '独立帐户负债' },
    { key: 'capitalDebt', project: '资本性负债' },
    { key: 'savingInvest', project: '保户储金及投资款' },
    { key: 'otherAcceptDebt', project: '其他认可负债' },
    { key: 'acceptDept', project: '认可负债' },
    { key: 'realAsset', project: '实际资本' },
    { key: 'coreAsset', project: '核心资本' },
    { key: 'lowestAsset', project: '最低资本' },
    { key: 'totalOverage', project: '综合偿付能力溢额' },
    { key: 'coreOverage', project: '核心偿付能力溢额' },
    { key: 'totalAbundant', project: '综合偿付能力充足率' },
    { key: 'coreAbundant', project: '核心偿付能力充足率' }
  ],
  forcastLowCapitalList,
  forcastLowCapitalkey: [
    {key: 'quantizationRisk', project: '量化风险最低资本'},
    {key: 'insureRisk', project: '保险风险最低资本'},
    {key: 'costRisk', project: '保费风险和准备金风险最低资本'},
    {key: 'carInsure', project: '其中：车险'},
    {key: 'finaInsure', project: '财产险'},
    {key: 'shipInsure', project: '船货特险'},
    {key: 'propertyInsure', project: '责任险'},
    {key: 'farmingInsure', project: '农业险'},
    {key: 'creditInsure', project: '信用保证险'},
    {key: 'shortYInsure', project: '短意险'},
    {key: 'shortJInsure', project: '短健险'},
    {key: 'shortSInsure', project: '短寿险'},
    {key: 'otherInsure', project: '其他险'},
    {key: 'largeRisk', project: '巨灾风险最低资本'},
    {key: 'marketRisk', project: '市场风险最低资本'},
    {key: 'rateRisk', project: '利率风险最低资本'},
    {key: 'profitRisk', project: '权益价格风险最低资本'},
    {key: 'housePriceRisk', project: '房地产价格风险最低资本'},
    {key: 'outIncomeRisk', project: '境外固定收益类资产价格风险最低资本'},
    {key: 'outProfitRisk', project: '境外权益类资产价格风险最低资本'},
    {key: 'exchangeRateRisk', project: '汇率风险最低资本'},
    {key: 'creditRisk', project: '信用风险最低资本'},
    {key: 'costOfCarryRisk', project: '利差风险最低资本'},
    {key: 'unTreatyRisk', project: '交易对手违约风险最低资本'},
    {key: 'controlRisk', project: '控制风险最低资本'},
    {key: 'attach', project: '附加资本'},
    {key: 'inverseAtt', project: '逆周期附加资本'},
    {key: 'inInsureAtt', project: '国内系统重要性保险机构附加资本'},
    {key: 'outImportantAtt', project: '国际系统重要性保险机构附加资本'},
    {key: 'otherAttach', project: '其他附加资本'},
    {key: 'lowestTotal', project: '最低资本合计'}
  ],
  payAbilityXlsx: [
    {project: '偿付能力压力测试表'},
    {project: '情景：基本情景'},
    {project: '公司：中华联合财产保险股份有限公司', reportYearLine: '报告年度：', reportSecondYear: '单位：万元'},
    {project: '项目', line: '行次', reportYearLine: '报告年度末', reportFirstYear: '报告年度后第一年', reportSecondYear: '报告年度后第二年'},
    {reportYearLine: '1', reportFirstYear: '2', reportSecondYear: '3'},
    ...JSON.parse(JSON.stringify(payAbilityList)),
    {project: '填表说明：'},
    {project: '（1）第1列填列根据保监会下发《保险公司偿付能力监管规则》第1号计算的报告年度各项目的实际值；第2列至第3列填列根据保监会下发《保险公司偿付能力监管规则》第1号及第10号填列各项目的预测值。'},
    {project: '（2） 保险公司应当区分基本情景和各种不利情景分别填列本表。不利情景无需填列第3列。'}
  ],
  forcastLowCapitalXlsx: [
    {line: '明细表偿付能力压力测试－9：预测最低资本表'},
    {line: '情景：基本情景'},
    {line: '公司：中华联合财产保险股份有限公司', reportYearLine: '报告年度：', reportSecondYear: '单位：万元'},
    {line: '行次', project: '项目', reportYearLine: '报告年度', reportFirstYear: '报告年度后第一年', reportSecondYear: '报告年度后第二年'},
    {reportYearLine: '1', reportFirstYear: '2', reportSecondYear: '3'},
    ...JSON.parse(JSON.stringify(forcastLowCapitalList)),
    {line: '填表说明：'},
    {line: '（1）第1列填列根据保监会下发《保险公司偿付能力监管规则》第2号、第3号、第4号、第5号及第7号计算的报告年度各项目的实际值；第2列至第3列填列根据保监会下发《保险公司偿付能力监管规则》第2号、第3号、第4号、第5号、第7号及第10号填列各项目的预测值。'},
    {line: '（2）保险公司应当区分基本情景和各种不利情景分别填列本表。不利情景无需填列第3列。'}
  ]
}
